### PR TITLE
Adding output file support, among other things

### PR DESCRIPTION
**Pull request by dolkensp**
Made some updates to ensure outputfile works - and that any directories are created as needed.

Changed a bunch of filename / path handling to ensure full paths were used where possible, and simplified file naming.

Changed default file naming convention to [infile]_out.obj

Added support for multiple input files

### CODE REVIEW

**Comment by Markemp** [comment]
I think some changes are needed, based on having to handle a special case with Star Citizen files.  It may apply for any newer (3.7+) Cryengine as well, but aside from Star Citizen I haven't run across these anywhere else.

There are .cga/.cgam pair files in Star Citizen, where the node chunks are stored in the .cga file, and the mesh info in the .cgam.  I have to read both of those objects into separate CgfData structures, and then figure out a way to consolidate the info so that it can be passed to the exporting classes.  With the sample batch upload, it'll end up reading those two files separately and processing them separately as well.  I'm not sure yet how this will impact the program.

The default naming convention ... need to think about that as well.  There are xml files that contain location information for game objects made up of various .cga pieces.  I use some powershell scripts to sort these out (and make some materials for blender), and I might have to change the default behavior for those as a result.

The full filename stuff is definitely something that needs to add.  Is it possible to accept part of a commit, or is it an all or nothing thing?

**Comment by dolkensp** [comment]
> Default naming convention

I changed it because there's quite a few directories where there's multiple LODs of objects, so if you batch process everything, you end up with the various LODs overwriting each other, because they're all the same object at different detail levels. With this naming convention, it ensures the file names are always unique to the file being converted.

I've moved it to a usage toggle (-noconflict for new functinoality - default is your root node version)

> With the sample batch upload, it'll end up reading those two files separately and processing them separately as well. I'm not sure yet how this will impact the program.

To be honest, this is behaving the same as it was before, it's just got the ability to add more files now. I haven't tried manually telling it to load more than 1 file, but the behavior for a single file (and a single file with associated cgam file) is the same. Main difference is instead of "InputFile1, InputFile2" you just have "InputFiles" now. I've just exported the entire SC PAK structure with this change, and all looks good on my end. We can experiment with assembling multiple cgas later.

> Full filename stuff

Just made one slight tweak to ensure the MTL file naming convention matches the obj file naming convention.

> The full filename stuff is definitely something that needs to add. Is it possible to accept part of a commit, or is it an all or nothing thing?

Not sure with pull requests - hopefully with the few things I changed, you can accept as is, give it a run, and roll back if you don't like it.

Let me know how you go!

Cheers,
Pete

**Comment by Markemp** [comment]
I totally forgot about the LODs!  The first thing I do when I extract the .pak files is to delete them all. :)  That's probably not the right answer, since there may be reasons to use them.

Going to accept the commit soon.  I'm finishing up solving the last of the geometry issues and want to get that done.  What a slog that has been.  It's amazing it ever worked before this!

**Comment by dolkensp** [comment]
I'd be interested in re-exporting the files back to CryEngine files once
they're in C# too - I haven't had a chance to take a good look yet, but is
that something you think is feasible with your implementation?

Would be nice to have a tool that just scrubs the files so they can be
imported into CryEngine / Blender / 3DS / Maya / etc - with OBJ and
CryEngine seeming like the easiest formats to start with.

**Comment by Markemp** [comment]
Re-exporting back into Cryengine is definitely possible.  The data structure is based on the Cryengine format.  Heck, you could probably pick the version of Cryengine you want to export to as well.

I really want to get the Collada exporter working though.  That can contain more advanced materials, armatures and animations.  Eventually I see this program taking one of the ship config XMLs and importing all the necessary parts (.caf files for animations, .chr for armature, etc), and exporting it into one file with everything included.  FBX or Collada are both good candidates for that.

**Comment by dolkensp** [comment]
Woo!

Did some more reading up on Collada - it seems like the ultimate file format to get working first!

WebGL appears to support it - at least, that's the format they're using here: https://aframe.io/examples/showcase/shopping/

That would mean I could pull the models and display them immediately on a website!

**Comment by Markemp** [comment]
Interesting... I wanted to get a WebGL exporter as well, but if they support Collada directly I might not have to export to another format!  My eventual goal is to have a website/mobile app that will let you select a ship/mech/tank, configure the loadout, camo pattern, weapons, colors, etc, and display that to the users.  Heck, once I get the animations exported maybe even have a list of animations for someone to play.  Basically the World of Warcraft model viewer for Cryengine games.

The COLLADA.cs file is the start of the Collada export.  I'm currently working on the mesh export if you want to take a look.  I'm using a library that allows for the serialization of Collada objects, which can easily be exported.  And makes creating the XML hierarchy pretty simple too.

**Comment by dolkensp** [comment]
Heh - I stumbled onto this project while working on
https://github.com/dolkensp/HoloXPLOR

Looks like you started with the models - I started with the Loadout / XML
parsing

**Comment by dolkensp** [comment]
It can currently import and export the Inventory.XML

I'm working out some kinks on the parsing of the other data XML files to
display the loadouts based off this reference image:
http://pre06.deviantart.net/736b/th/pre/f/2013/075/2/2/star_citizen___roberts_space_industries_ship_ui_by_z_design-d5y7x1m.jpg

You need to dump the Scripts.XML files in the App_Data folder, you'll see
from the missing files (I don't check in app_data so I don't leak any
personal / proprietary assets)

**Pull request merged**
