### PR TITLE
Fix for SC 3.23 changes

### PR DESCRIPTION
**Pull request by Markemp**
- Fix issue with submesh chunk changes for 3.23.  The material ID changed from an int to an int16, with the second half set to 0xFFFF.  As a result, it was reading negative numbers and throwing an error when trying to look up the index for that material.

### CODE REVIEW

**Comment by Baconator650** [comment]
Did some testing, seems to be working...now those animations now :-p

**Comment by Markemp** [comment]
> Did some testing, seems to be working...now those animations now :-p

I'm actually back working on this, but as part of a USD upgrade.  USD support is now to the level where armatures and animations are viable, and Blender is going to axe Collada in 4.5... 5.0 at the latest.  It's time to get this going again.

**Comment by Baconator650** [comment]
Oh this is exciting, I actually have a good number of the ships from Star Citizen Build 3.8 with the animation converted over to my max files  (stilll working on the Hammerhead, Reclaimer, Carrack, 890J). I know there are still some challenges with the IVO format and accessing the animation database, but it looks like one of the new guys (Diogo Trindade) may have a solution for it. Looking forward to developing the workflow for some users with this.

**Comment by Baconator650** [comment]
> > Did some testing, seems to be working...now those animations now :-p
> 
> I'm actually back working on this, but as part of a USD upgrade. USD support is now to the level where armatures and animations are viable, and Blender is going to axe Collada in 4.5... 5.0 at the latest. It's time to get this going again.

How's the progress going?

**Comment by Markemp** [comment]
Not bad!  I posted another discussion with the USD branch that I'm working on.  Got basic geometry working.  Trying to get materials in a better place.  Then off to armatures, and animations after that.

**Pull request merged**
